In [61]:
import numpy as np
import h5py
import sys
sys.path.insert(0, '../scripts/logistic_gpu/')
import logistic_gpu
import imp
logistic_gpu = imp.reload(logistic_gpu)
import torch

In [4]:
y = np.load('../scripts/logistic_gpu/cached_y.npy')
indiv_index = np.load('../scripts/logistic_gpu/cached_indiv_index.npy')
C = np.load('../scripts/logistic_gpu/cached_covar.npy')
z = np.load('../scripts/logistic_gpu/cached_z.npy')


In [5]:
# failed at 151/238

In [25]:
step_size = 100
with h5py.File('/vol/bmd/yanyul/UKB/ukb_hap_v2_to_hdf5/ukb_hap_v2_to_hdf5.chr16.h5', 'r') as f:
    genotype = f['genotype'][:, (151 * step_size) : (152 * step_size), :]
    

In [26]:
genotype = genotype[:, :, indiv_index]

In [27]:
h1 = genotype[0, :, :].T
h2 = genotype[1, :, :].T

In [62]:
solver = logistic_gpu.BatchLogisticSolver()

In [72]:
o1 = solver.batchIRLS(
    torch.Tensor(h1 + h2) / 2,
    torch.Tensor(y)[:, 0],
    torch.Tensor(C),
    min_prob=1e-7,
    use_mask=True
)

0 tensor(0.) tensor(1.)
1 tensor(0.5000) tensor(0.5000)
2 tensor(0.2513) tensor(0.1172)
3 tensor(0.2312) tensor(0.0408)
4 tensor(0.2836) tensor(0.0148)
5 tensor(0.2836) tensor(0.0054)
6 tensor(0.2836) tensor(0.0020)
7 tensor(0.2836) tensor(0.0007)
8 tensor(0.2836) tensor(0.0003)
9 tensor(0.2836) tensor(9.8586e-05)
10 tensor(0.2836) tensor(3.6240e-05)
11 tensor(0.2836) tensor(1.3351e-05)
12 tensor(0.2836) tensor(4.8876e-06)
13 tensor(0.2836) tensor(1.7881e-06)
14 tensor(0.2836) tensor(7.1526e-07)
15 tensor(0.2836) tensor(2.3842e-07)
16 tensor(0.2836) tensor(1.1921e-07)
tensor(99)
tensor(99)


In [67]:
np.where(o1[1][1] < 0)

(array([80]),)

In [69]:
sanity_sum_o = np.load('../scripts/logistic_gpu/test_sanity_sum.npy')

In [108]:
sanity_sum_o[:, 0, (151 * step_size) + 80]

array([0., 0., 0.], dtype=float32)

In [80]:
o2 = sanity_sum_o[:, 0, (151 * step_size)  : (152 * step_size)]

In [107]:
o1[0][-1][o2[2] == 1] / torch.Tensor(o2[0][o2[2] == 1])

tensor([1.9999, 2.0001, 2.0000, 2.0000, 2.0000, 2.0001, 2.0000, 2.0000, 2.0000,
        2.0000, 1.9999, 2.0000, 2.0000, 2.0000, 2.0000, 2.0001, 2.0000, 2.0000,
        2.0000, 2.0000, 2.0000, 2.0000, 2.0000, 2.0001, 2.0000, 2.0000, 2.0000,
        2.0000, 2.0000, 2.0000, 1.9998, 2.0001, 1.9999, 2.0000, 2.0000, 2.0003,
        2.0000, 2.0000, 2.0000, 2.0000, 2.0000, 2.0000, 2.0000, 2.0000, 2.0000,
        2.0000, 2.0000, 1.9998, 2.0000, 2.0000, 2.0000, 2.0000, 2.0000, 2.0000,
        2.0000, 2.0000, 2.0000, 2.0000, 2.0000, 2.0001, 1.9999, 2.0000, 2.0000,
        2.0000, 2.0000, 2.0000, 2.0000, 2.0001, 2.0000, 2.0000, 2.0000, 2.0000,
        2.0001, 2.0000, 2.0000, 2.0000])

In [103]:
o1[0][-1][o1[2] == 1] 

tensor([-9.3546e-03, -6.7488e-01, -3.5434e-03,  2.1237e-02, -2.0741e-03,
         1.6016e-02,  2.7786e-03,  4.2543e-02, -3.5270e-02,  3.0130e-02,
        -3.0738e-02, -8.0485e-02,  6.1978e-04,  1.0003e-01,  3.7623e-02,
         6.0890e-02, -4.9444e-02, -4.2904e-02,  1.3752e-02, -8.0676e-03,
        -7.3872e-02, -1.5683e-02,  1.1558e-02,  2.0010e-02,  2.9902e-02,
        -8.5903e-02,  3.3020e-02,  2.1279e-02,  1.6756e-02,  2.1755e-02,
         2.1025e-02, -9.8523e-03,  2.8137e-02, -1.5432e-01, -2.4284e-02,
        -1.0043e-02, -1.1861e-03,  1.8086e-02,  1.6840e-02, -6.0068e-02,
         4.1041e-02,  1.2430e-02, -4.1000e-03, -3.7367e-02,  1.7676e-02,
        -1.0711e-01, -1.0975e-01,  7.3174e-03,  1.7799e-02, -2.4378e-02,
         1.3596e-02, -9.0767e-03,  3.8524e-02,  1.5505e-02,  1.5152e-02,
         3.1329e-01,  1.8470e-03,  3.0215e-01, -8.0245e-02,  2.4947e-02,
         2.9417e-02,  3.0454e-02, -6.6132e-01,  5.5379e-02,  4.1905e-02,
         2.1524e-01,  1.5753e-02, -4.2224e-02, -1.8

In [105]:
torch.Tensor(o2[0][o1[2] == 1])

tensor([-0.0047,  0.0000, -0.0018,  0.0106, -0.0010,  0.0080,  0.0014,  0.0213,
        -0.0176,  0.0151,  0.0000, -0.0402,  0.0003,  0.0000,  0.0188,  0.0304,
        -0.0247, -0.0215,  0.0069, -0.0040, -0.0369, -0.0078,  0.0058,  0.0100,
         0.0150,  0.0000,  0.0165,  0.0106,  0.0084,  0.0109,  0.0105, -0.0049,
         0.0000,  0.0000, -0.0121, -0.0050, -0.0006,  0.0090,  0.0084,  0.0000,
         0.0205,  0.0062, -0.0020, -0.0187,  0.0088,  0.0000, -0.0549,  0.0037,
         0.0089, -0.0122,  0.0068, -0.0045,  0.0193,  0.0078,  0.0076,  0.0000,
         0.0009,  0.0000,  0.0000,  0.0125,  0.0147,  0.0152,  0.0000,  0.0277,
         0.0210,  0.0000,  0.0079, -0.0211,  0.0000, -0.0222,  0.0000,  0.0000,
         0.0000,  0.0063, -0.0154,  0.0000,  0.0109, -0.0013,  0.0027,  0.0198,
        -0.0282, -0.0077,  0.0000, -0.0270, -0.0231,  0.0378, -0.0013,  0.0000,
        -0.0120, -0.0051, -0.0117,  0.0000,  0.0060,  0.0024,  0.0436, -0.0098,
         0.0000,  0.0000,  0.0253])

In [97]:
torch.Tensor(o2[0][o1[2] == 1]).shape

torch.Size([99])

In [101]:
o1[0][-1][o1[2] == 1] .shape

torch.Size([99])

In [100]:
o1[0].shape

torch.Size([12, 100])

In [106]:
o2[2]

array([1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 0., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 0., 0.,
       1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 0., 1., 0., 0., 1., 1., 1., 0., 1., 1., 0., 1., 1.,
       0., 1., 0., 0., 0., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 0., 1.,
       1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 1., 0., 0., 1.],
      dtype=float32)